root: ${paths.data_dir}/TAL-NoiseMaker/parameter_variations

# available_variations:
#   - amp_attack
#   - amp_decay
#   - filter_cutoff
#   - filter_decay
#   - filter_resonance
#   - frequency_mod
#   - lfo_amount_on_filter
#   - lfo_amount_on_volume
#   - lfo_rate_on_filter
#   - lfo_rate_on_volume
#   - pitch_coarse
#   - reverb