relative_pairwise_dists:
  # Compute the nearest neighbors of `num_samples` randomly chosen samples
  # and log them in a wandb.Table

  # number of samples to compute the nearest neighbors for
  num_samples: 10
  
  # Number of neighbors to log.
  n_neighbors: 5
  
  # modes for selecting the neighbors.
  mode: 
    - nearest # nearest neighbors
    
    # - farthest # farthest neighbors
    
    # log n neighbors equally spaced between the first 
    # and the last element of the indices.
    - linspace