encoder: 
  _target_: models.audiomae.audiomae_wrapper.AudioMAEWrapper
  ckpt_name: as-2M_pt+ft
  contextual_depth: 8
  class_token: true

name: audio-mae_${.encoder.ckpt_name}_${.encoder.contextual_depth}_${.encoder.class_token}
group: audio-mae