encoder: 
  _target_: models.encodec.encoder.EncodecEncoder.encodec_model_24khz
  repository: ${paths.ckpt_dir}
  # segment: ${audio_length}
  overlap: 0.0

name: "encodec_24khz"
input_repr: "waveform"

