# @package _global_

defaults:
  - _self_
  #- data: nsynth 
  - hydra: default
  - logger: wandb
  - model: encodec48khz
  - eval/nearest_neighbors: default # pass null to omit
  - eval/parameter_variations: tal_noisemaker
  - paths: default 

  # experiment to perform (concret ones, not debug ones)
  - experiment: null

  # debug options
  - debug: null

# seed for random number generators in pytorch, numpy and python.random
seed: 667

# this will be use to set the model`s input frame length 
# as well as padding/truncating the audio data
audio_length: 4.0

# similarity function to use for all evaluation
similarity_fn: pairwise_manhattan_distance

# function used to reduce the embedding dimensionality
# available options: flatten, global_avg_pool_channel, global_avg_pool_time, 
# global_max_pool_channel, global_max_pool_time
reduce_fn: flatten

# task name, determines output directory path
task_name: ${model.name}











