# @package _global_

defaults:
  - _self_

  # hydra config
  - hydra: default

  # wandb logger config
  - wandb: default

  # model to evaluate
  - model: openl3_mel256_music_6144 #encodec48khz
  
  # evaluation to perform
  - eval/nearest_neighbors: null # default # pass null to omit
  - eval/sound_attributes_ranking: tal_noisemaker

  # function used to calculate the distance matrix of the sound embeddings 
  # (must be the name of a torchmetrics.functional function)
  - distance_fn: pairwise_manhattan_distance

  # function used to reduce the embedding dimensionality
  - reduce_fn: flatten

  # paths related config
  - paths: default 

  # experiment to perform (concret ones, not debug ones)
  - experiment: null

  # debug options
  - debug: null

# seed for random number generators in pytorch, numpy and python.random
seed: 667

# this will be use to set the model`s input frame length 
# as well as padding/truncating the audio data
# actually not needed
# audio_length: 4.0


# task name, determines output directory path
task_name: ${model.name}











